allowBuilds:
  core-js: false

minimumReleaseAge: 30240 # 21 days, as per policy

minimumReleaseAgeExclude:
  - "@adyen/*"
  # Renovate security update: vitest@4.1.11
  - vitest@4.1.11
  - js-yaml@3.15.2 #CVE

saveExact: true

trustPolicy: no-downgrade

verifyDepsBeforeRun: install
